{
    ApprenticeEvents();
    MTrainingEvents();
    FarmHandEvents();
    FTrainingEvents();
    GuardDutyEvents();
    STrainingEvents();
    CarouseEvents();
    TTrainingEvents();
    GravekeepingEvents();
    GraverobbingEvents();
    PageWorkEvents();
    THTrainingEvents();
    MayorWorkEvents();

    globalvar TL_Apprentice;
    TL_Apprentice = ds_map_create();
    ds_map_add(TL_Apprentice,'name','Apprentice (0G)');
    ds_map_add(TL_Apprentice,'intellect',4);
    ds_map_add(TL_Apprentice,'fortitude',2);
    ds_map_add(TL_Apprentice,'reqList',TE_ApprenticeEvents);
    ds_map_add(TL_Apprentice,'randList',TE_ApprenticeREvents);
    ds_map_add(TL_Apprentice,'basicText','spends the week doing odd jobs for smelly wizards.');
    ds_map_add(TL_Apprentice,'basicGold',100);
    ds_map_add(TL_Apprentice,'viewX',288);
    ds_map_add(TL_Apprentice,'viewY',128);
    ds_map_add(TL_Apprentice,'heroX',352);
    ds_map_add(TL_Apprentice,'heroY',164);
    
    globalvar TL_MageTraining;
    TL_MageTraining = ds_map_create();
    ds_map_add(TL_MageTraining,'name','Training');
    ds_map_add(TL_MageTraining,'intellect',10);
    ds_map_add(TL_MageTraining,'reqList',TE_MTrainingEvents);
    ds_map_add(TL_MageTraining,'randList',TE_MTrainingREvents);
    ds_map_add(TL_MageTraining,'basicText','sits down with the Archmage for some one-on-one training.');
    ds_map_add(TL_MageTraining,'basicGold',-500);
    ds_map_add(TL_MageTraining,'viewX',288);
    ds_map_add(TL_MageTraining,'viewY',128);
    ds_map_add(TL_MageTraining,'heroX',352);
    ds_map_add(TL_MageTraining,'heroY',164);
    
    globalvar TL_FarmHand;
    TL_FarmHand = ds_map_create();
    ds_map_add(TL_FarmHand,'name','Farmhand (0G)');
    ds_map_add(TL_FarmHand,'strength',2);
    ds_map_add(TL_FarmHand,'fortitude',4);
    ds_map_add(TL_FarmHand,'reqList',TE_FarmHandEvents);
    ds_map_add(TL_FarmHand,'randList',TE_FarmHandREvents);
    ds_map_add(TL_FarmHand,'basicText','helps out with the harvest at the local farm.');
    ds_map_add(TL_FarmHand,'basicGold',200);
    ds_map_add(TL_FarmHand,'viewX',288);
    ds_map_add(TL_FarmHand,'viewY',0);
    ds_map_add(TL_FarmHand,'heroX',360);
    ds_map_add(TL_FarmHand,'heroY',24);
    
    globalvar TL_FarmTraining;
    TL_FarmTraining = ds_map_create();
    ds_map_add(TL_FarmTraining,'name','Training');
    ds_map_add(TL_FarmTraining,'strength',3);
    ds_map_add(TL_FarmTraining,'fortitude',7);
    ds_map_add(TL_FarmTraining,'reqList',TE_FTrainingEvents);
    ds_map_add(TL_FarmTraining,'randList',TE_FTrainingREvents);
    ds_map_add(TL_FarmTraining,'basicText','pays for the privilege of an intensive farm workout.');
    ds_map_add(TL_FarmTraining,'basicGold',-500);
    ds_map_add(TL_FarmTraining,'viewX',288);
    ds_map_add(TL_FarmTraining,'viewY',0);
    ds_map_add(TL_FarmTraining,'heroX',360);
    ds_map_add(TL_FarmTraining,'heroY',24);
    
    globalvar TL_GuardDuty;
    TL_GuardDuty = ds_map_create();
    ds_map_add(TL_GuardDuty,'name','Guard Duty (0G)');
    ds_map_add(TL_GuardDuty,'strength',4);
    ds_map_add(TL_GuardDuty,'accuracy',2);
    ds_map_add(TL_GuardDuty,'reqList',TE_GuardDutyEvents);
    ds_map_add(TL_GuardDuty,'randList',TE_GuardDutyREvents);
    ds_map_add(TL_GuardDuty,'basicText','patrols the town and beats up the local ruffians.');
    ds_map_add(TL_GuardDuty,'basicGold',200);
    ds_map_add(TL_GuardDuty,'viewX',448);
    ds_map_add(TL_GuardDuty,'viewY',128);
    ds_map_add(TL_GuardDuty,'heroX',520);
    ds_map_add(TL_GuardDuty,'heroY',144);
    
    globalvar TL_SoldierTraining;
    TL_SoldierTraining = ds_map_create();
    ds_map_add(TL_SoldierTraining,'name','Training');
    ds_map_add(TL_SoldierTraining,'strength',10);
    ds_map_add(TL_SoldierTraining,'reqList',TE_STrainingEvents);
    ds_map_add(TL_SoldierTraining,'randList',TE_STrainingREvents);
    ds_map_add(TL_SoldierTraining,'basicText','hangs out in the barracks and trains day and night.');
    ds_map_add(TL_SoldierTraining,'basicGold',-500);
    ds_map_add(TL_SoldierTraining,'viewX',448);
    ds_map_add(TL_SoldierTraining,'viewY',128);
    ds_map_add(TL_SoldierTraining,'heroX',520);
    ds_map_add(TL_SoldierTraining,'heroY',144);
    
    globalvar TL_Carouse;
    TL_Carouse = ds_map_create();
    ds_map_add(TL_Carouse,'name','Carouse (0G)');
    ds_map_add(TL_Carouse,'accuracy',4);
    ds_map_add(TL_Carouse,'charm',2);
    ds_map_add(TL_Carouse,'reqList',TE_CarouseEvents);
    ds_map_add(TL_Carouse,'randList',TE_CarouseREvents);
    ds_map_add(TL_Carouse,'basicText','spends the week in the tavern, drinking, gambling, and playing darts.');
    ds_map_add(TL_Carouse,'basicGold',0);
    ds_map_add(TL_Carouse,'viewX',448);
    ds_map_add(TL_Carouse,'viewY',256);
    ds_map_add(TL_Carouse,'heroX',480);
    ds_map_add(TL_Carouse,'heroY',280);
    
    globalvar TL_TavernTraining;
    TL_TavernTraining = ds_map_create();
    ds_map_add(TL_TavernTraining,'name','Training');
    ds_map_add(TL_TavernTraining,'accuracy',10);
    ds_map_add(TL_TavernTraining,'reqList',TE_TTrainingEvents);
    ds_map_add(TL_TavernTraining,'randList',TE_TTrainingREvents);
    ds_map_add(TL_TavernTraining,'basicText','buys drinks for other heroes and gets tips on his technique.');
    ds_map_add(TL_TavernTraining,'basicGold',-500);
    ds_map_add(TL_TavernTraining,'viewX',448);
    ds_map_add(TL_TavernTraining,'viewY',256);
    ds_map_add(TL_TavernTraining,'heroX',480);
    ds_map_add(TL_TavernTraining,'heroY',280);
    
    globalvar TL_Gravekeeping;
    TL_Gravekeeping = ds_map_create();
    ds_map_add(TL_Gravekeeping,'name','Gravekeeping (0G)');
    ds_map_add(TL_Gravekeeping,'fortitude',4);
    ds_map_add(TL_Gravekeeping,'accuracy',2);
    ds_map_add(TL_Gravekeeping,'reqList',TE_GravekeepingEvents);
    ds_map_add(TL_Gravekeeping,'randList',TE_GravekeepingREvents);
    ds_map_add(TL_Gravekeeping,'basicText','patrols the graveyard every night, keeping the dead in their graves.');
    ds_map_add(TL_Gravekeeping,'basicGold',200);
    ds_map_add(TL_Gravekeeping,'viewX',288);
    ds_map_add(TL_Gravekeeping,'viewY',256);
    ds_map_add(TL_Gravekeeping,'heroX',352);
    ds_map_add(TL_Gravekeeping,'heroY',288);
    
    globalvar TL_Graverobbing;
    TL_Graverobbing = ds_map_create();
    ds_map_add(TL_Graverobbing,'name','Rob Graves (0G)');
    ds_map_add(TL_Graverobbing,'',0);
    ds_map_add(TL_Graverobbing,'reqList',TE_GraverobbingEvents);
    ds_map_add(TL_Graverobbing,'randList',TE_GraverobbingREvents);
    ds_map_add(TL_Graverobbing,'basicText','digs up bodies and takes their gold fillings, making a tidy profit.');
    ds_map_add(TL_Graverobbing,'basicGold',500);
    ds_map_add(TL_Graverobbing,'viewX',288);
    ds_map_add(TL_Graverobbing,'viewY',256);
    ds_map_add(TL_Graverobbing,'heroX',352);
    ds_map_add(TL_Graverobbing,'heroY',288);
    
    globalvar TL_PageWork;
    TL_PageWork = ds_map_create();
    ds_map_add(TL_PageWork,'name','Page Duty (0G)');
    ds_map_add(TL_PageWork,'charm',4);
    ds_map_add(TL_PageWork,'intellect',2);
    ds_map_add(TL_PageWork,'reqList',TE_PageWorkEvents);
    ds_map_add(TL_PageWork,'randList',TE_PageWorkREvents);
    ds_map_add(TL_PageWork,'basicText','runs errands for the various bureaucrats that manage the town.');
    ds_map_add(TL_PageWork,'basicGold',300);
    ds_map_add(TL_PageWork,'viewX',448);
    ds_map_add(TL_PageWork,'viewY',0);
    ds_map_add(TL_PageWork,'heroX',520);
    ds_map_add(TL_PageWork,'heroY',32);
    
    globalvar TL_MayorWork;
    TL_MayorWork = ds_map_create();
    ds_map_add(TL_MayorWork,'name','Mayoral Duty (0G)');
    ds_map_add(TL_MayorWork,'charm',4);
    ds_map_add(TL_MayorWork,'intellect',2);
    ds_map_add(TL_MayorWork,'reqList',TE_MayorWorkEvents);
    ds_map_add(TL_MayorWork,'randList',TE_MayorWorkREvents);
    ds_map_add(TL_MayorWork,'basicText','manages the town protocols and finances from behind his mayoral desk.');
    ds_map_add(TL_MayorWork,'basicGold',500);
    ds_map_add(TL_MayorWork,'viewX',448);
    ds_map_add(TL_MayorWork,'viewY',0);
    ds_map_add(TL_MayorWork,'heroX',500);
    ds_map_add(TL_MayorWork,'heroY',36);
    
    globalvar TL_THTraining;
    TL_THTraining = ds_map_create();
    ds_map_add(TL_THTraining,'name','Training');
    ds_map_add(TL_THTraining,'charm',10);
    ds_map_add(TL_THTraining,'reqList',TE_THTrainingEvents);
    ds_map_add(TL_THTraining,'randList',TE_THTrainingREvents);
    ds_map_add(TL_THTraining,'basicText','spends expensive quality time with the town Chancellor every day.');
    ds_map_add(TL_THTraining,'basicGold',-500);
    ds_map_add(TL_THTraining,'viewX',448);
    ds_map_add(TL_THTraining,'viewY',0);
    ds_map_add(TL_THTraining,'heroX',520);
    ds_map_add(TL_THTraining,'heroY',32);

}